### ISSUE TITLE
Support using zip with country

### ISSUE THREAD

**Issue by johnwc** [MarkCiliaVincenti/OpenWeatherMap.Cache#2]
Can you add another location class that supports location based on zip and country like OpenWeatherMap api supports?

**Comment by MarkCiliaVincenti** [comment]
Thanks, done and released in 1.4.0 (also available on NuGet.org)

Please use the OpenWeatherMap.Cache.ZipCode class.

**Comment by johnwc** [comment]
We are using it in an internal application where we need to track the current locations local weather and record it.
