### ISSUE TITLE
Suggest using decimal over double or float

### ISSUE THREAD

**Issue by johnwc** [MarkCiliaVincenti/OpenWeatherMap.Cache#3]
You're currently using UnitsNet for temp and humidity, which uses double for the values. For precision and to make sure the value is exactly the same from source to client, I would recommend using decimal. It will guarantee that any value from the OpenWeather service is exactly the same in whatever client is using your library.

**Comment by MarkCiliaVincenti** [comment]
Can you please find me a practical example? We're talking about numeric values that will have one decimal figure. UnitsNet is an industry standard library used even by official Microsoft packages such as https://www.nuget.org/packages/Microsoft.IoT.Devices

**Comment by johnwc** [comment]
Industry standard in what industry? This is the first time I've ever seen it. And I wouldn't use a Microsoft library as a standard, they flip-flop between library usage all the time. Look at their constant JSON libraries they go back and forth on.

For a simple example of the odd things that floating points give you: [.NET C# float.Parse returning different result to double.Parse](https://stackoverflow.com/questions/51988467/net-c-sharp-float-parse-returning-different-result-to-double-parse) It may be single decimal from OpenWeather, but when you need to calculate on it like converting it to/from C and F... 

It's just a suggestion, I personally try to use decimal, as it has bitten me in the rear end in the past when floats cause the math to be incorrect.

**Comment by MarkCiliaVincenti** [comment]
I'm sorry, but I've chosen to take the UnitsNet approach from the very start, specifically because I wanted to have the tried-and-tested approach to the conversions needed and without having to reinvent the wheel myself. Also, it's using double not float. We are dealing with approximations anyway. This is not financial data.
